#
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
# This file has been auto-generated by the confdc compiler.
# Source: ../load-dir/l3vpn-svc.fxs
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
#

# Autogenerated namespace class for YANG module l3vpn-svc.yang


class ns(object):
    hash = 1279167971

    id = "_nokia-nsp-l3vpn-nc-1.0:nokia-nsp-l3vpn-nc-1.0#http://www.nokia.com/ietf-l3vpn-ntw:l3vpn-ntw/vpn-services"

    uri = "_nokia-nsp-l3vpn-nc-1.0:nokia-nsp-l3vpn-nc-1.0#http://www.nokia.com/ietf-l3vpn-ntw:l3vpn-ntw/vpn-services"

    prefix = "l3vpn-svc"

    l3vpn_svc_routing_protocols = 1456255638
    l3vpn_svc_routing_protocols_ = "routing-protocols"
    l3vpn_svc_ipv4 = 268057062
    l3vpn_svc_ipv4_ = "ipv4"
    l3vpn_svc_connection = 1134114300
    l3vpn_svc_connection_ = "connection"
    l3vpn_svc_svc_output_bandwidth = 1065362088
    l3vpn_svc_svc_output_bandwidth_ = "svc-output-bandwidth"
    l3vpn_svc_devices = 270307409
    l3vpn_svc_devices_ = "devices"
    l3vpn_svc_vpn_target = 481105398
    l3vpn_svc_vpn_target_ = "vpn-target"
    l3vpn_svc_peer_status = 2008420880
    l3vpn_svc_peer_status_ = "peer-status"
    l3vpn_svc_vpn_attachment = 363199070
    l3vpn_svc_vpn_attachment_ = "vpn-attachment"
    l3vpn_svc_site_id = 1504125779
    l3vpn_svc_site_id_ = "site-id"
    l3vpn_svc_dot1q_vlan_tagged = 193818157
    l3vpn_svc_dot1q_vlan_tagged_ = "dot1q-vlan-tagged"
    l3vpn_svc_l3vpn_svc = 593629653
    l3vpn_svc_l3vpn_svc_ = "l3vpn-svc"
    l3vpn_svc_location = 1827424758
    l3vpn_svc_location_ = "location"
    l3vpn_svc_vpn_service = 1055968467
    l3vpn_svc_vpn_service_ = "vpn-service"
    l3vpn_svc_address_allocation_type = 1985129786
    l3vpn_svc_address_allocation_type_ = "address-allocation-type"
    l3vpn_svc_site_role = 1195406870
    l3vpn_svc_site_role_ = "site-role"
    l3vpn_svc_sites = 280052322
    l3vpn_svc_sites_ = "sites"
    l3vpn_svc_site_network_access_id = 1100367278
    l3vpn_svc_site_network_access_id_ = "site-network-access-id"
    l3vpn_svc_vpn_policy_id = 182903099
    l3vpn_svc_vpn_policy_id_ = "vpn-policy-id"
    l3vpn_svc_device = 617911018
    l3vpn_svc_device_ = "device"
    l3vpn_svc_vpn_policy = 1025722019
    l3vpn_svc_vpn_policy_ = "vpn-policy"
    l3vpn_svc_site_network_accesses = 1757943133
    l3vpn_svc_site_network_accesses_ = "site-network-accesses"
    l3vpn_svc_addresses = 1825332052
    l3vpn_svc_addresses_ = "addresses"
    l3vpn_svc_status = 1950810920
    l3vpn_svc_status_ = "status"
    l3vpn_svc_site_network_access = 1354428188
    l3vpn_svc_site_network_access_ = "site-network-access"
    l3vpn_svc_vpn_targets = 140988191
    l3vpn_svc_vpn_targets_ = "vpn-targets"
    l3vpn_svc_vpn_services = 420699127
    l3vpn_svc_vpn_services_ = "vpn-services"
    l3vpn_svc_device_id = 669279939
    l3vpn_svc_device_id_ = "device-id"
    l3vpn_svc_locations = 1179950026
    l3vpn_svc_locations_ = "locations"
    l3vpn_svc_tagged_interface = 1105325482
    l3vpn_svc_tagged_interface_ = "tagged-interface"
    l3vpn_svc_address_family = 203507431
    l3vpn_svc_address_family_ = "address-family"
    l3vpn_svc_svc_mtu = 59128295
    l3vpn_svc_svc_mtu_ = "svc-mtu"
    l3vpn_svc_entries = 1782358652
    l3vpn_svc_entries_ = "entries"
    l3vpn_svc_vpn_policies = 2070014031
    l3vpn_svc_vpn_policies_ = "vpn-policies"
    l3vpn_svc_rd = 1976848467
    l3vpn_svc_rd_ = "rd"
    l3vpn_svc_type = 2040883914
    l3vpn_svc_type_ = "type"
    l3vpn_svc_peer_as = 542003455
    l3vpn_svc_peer_as_ = "peer-as"
    l3vpn_svc_vpn_id = 1043646672
    l3vpn_svc_vpn_id_ = "vpn-id"
    l3vpn_svc_port_id = 411479338
    l3vpn_svc_port_id_ = "port-id"
    l3vpn_svc_router_id = 519485925
    l3vpn_svc_router_id_ = "router-id"
    l3vpn_svc_peer_description = 1747769655
    l3vpn_svc_peer_description_ = "peer-description"
    l3vpn_svc_autonomous_system = 299737889
    l3vpn_svc_autonomous_system_ = "autonomous-system"
    l3vpn_svc_management = 1308506682
    l3vpn_svc_management_ = "management"
    l3vpn_svc_svc_input_bandwidth = 1555967831
    l3vpn_svc_svc_input_bandwidth_ = "svc-input-bandwidth"
    l3vpn_svc_admin_enabled = 1699111814
    l3vpn_svc_admin_enabled_ = "admin-enabled"
    l3vpn_svc_ip_connection = 789735093
    l3vpn_svc_ip_connection_ = "ip-connection"
    l3vpn_svc_service = 855380710
    l3vpn_svc_service_ = "service"
    l3vpn_svc_provider_address = 1039400294
    l3vpn_svc_provider_address_ = "provider-address"
    l3vpn_svc_vpn = 1300042178
    l3vpn_svc_vpn_ = "vpn"
    l3vpn_svc_tq_type = 1407941797
    l3vpn_svc_tq_type_ = "tq-type"
    l3vpn_svc_location_id = 517526331
    l3vpn_svc_location_id_ = "location-id"
    l3vpn_svc_site_bearer = 292121906
    l3vpn_svc_site_bearer_ = "site-bearer"
    l3vpn_svc_route_target_type = 1412747313
    l3vpn_svc_route_target_type_ = "route-target-type"
    l3vpn_svc_cvlan_id = 1965303353
    l3vpn_svc_cvlan_id_ = "cvlan-id"
    l3vpn_svc_site = 407467135
    l3vpn_svc_site_ = "site"
    l3vpn_svc_device_reference = 500432060
    l3vpn_svc_device_reference_ = "device-reference"
    l3vpn_svc_encapsulation_type = 671206547
    l3vpn_svc_encapsulation_type_ = "encapsulation-type"
    l3vpn_svc_routing_protocol = 667412728
    l3vpn_svc_routing_protocol_ = "routing-protocol"
    l3vpn_svc_route_target = 472721783
    l3vpn_svc_route_target_ = "route-target"
    l3vpn_svc_id = 1279252765
    l3vpn_svc_id_ = "id"
    l3vpn_svc_peer_address = 2130238605
    l3vpn_svc_peer_address_ = "peer-address"
    l3vpn_svc_bearer = 1710416560
    l3vpn_svc_bearer_ = "bearer"
    l3vpn_svc_prefix_length = 524393771
    l3vpn_svc_prefix_length_ = "prefix-length"
