#
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
# This file has been auto-generated by the confdc compiler.
# Source: ../load-dir/tailf-ned-id-nokia-nsp-l3vpn-nc-1.0.fxs
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
#

# Autogenerated namespace class for YANG module tailf-ned-id-nokia-nsp-l3vpn-nc-1.0.yang


class ns(object):
    hash = 13225761

    id = "http://tail-f.com/ns/ned-id/nokia-nsp-l3vpn-nc-1.0"

    uri = "http://tail-f.com/ns/ned-id/nokia-nsp-l3vpn-nc-1.0"

    prefix = "nokia-nsp-l3vpn-nc-1.0"

    nokia_nsp_l3vpn_nc_10x2e0_nokia_nsp_l3vpn_nc_10x2e0 = 1075548468
    nokia_nsp_l3vpn_nc_10x2e0_nokia_nsp_l3vpn_nc_10x2e0_ = "nokia-nsp-l3vpn-nc-1.0"
