#
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
# This file has been auto-generated by the confdc compiler.
# Source: ../load-dir/tailf-ned-id-nokia-nsp-l3vpn-nc.fxs
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
#

# Autogenerated namespace class for YANG module tailf-ned-id-nokia-nsp-l3vpn-nc.yang


class ns(object):
    hash = 1695637270

    id = "http://tail-f.com/ns/ned-id/nokia-nsp-l3vpn-nc"

    uri = "http://tail-f.com/ns/ned-id/nokia-nsp-l3vpn-nc"

    prefix = "nokia-nsp-l3vpn-nc"

    nokia_nsp_l3vpn_nc_nokia_nsp_l3vpn_nc = 419531738
    nokia_nsp_l3vpn_nc_nokia_nsp_l3vpn_nc_ = "nokia-nsp-l3vpn-nc"
    ned_id = 419531738
    ned_id_ = "nokia-nsp-l3vpn-nc:nokia-nsp-l3vpn-nc"
