/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ../load-dir/ietf-ethernet-segment.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.example.bessevpn.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module ietf-ethernet-segment.yang */
public class ietfEthernetSegment extends ConfNamespace {
    public static final int hash = 1552592713;
    public int hash() {
        return ietfEthernetSegment.hash;
    }

    public static final String id = "_bessevpn-nc-1.0:bessevpn-nc-1.0#urn:ietf:params:xml:ns:yang:ietf-ethernet-segment";
    public String id() {
        return ietfEthernetSegment.id;
    }

    public static final String uri = "_bessevpn-nc-1.0:bessevpn-nc-1.0#urn:ietf:params:xml:ns:yang:ietf-ethernet-segment";
    public String uri() {
        return ietfEthernetSegment.uri;
    }

    public String xmlUri() {
        return ConfNamespace.truncateToXMLUri(ietfEthernetSegment.uri);
    }

    public static final String prefix = "es";
    public String prefix() {
        return ietfEthernetSegment.prefix;
    }

    public ietfEthernetSegment() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

    public static final int    _ethernet_segment_identifier = 449467648;
    public static final String _ethernet_segment_identifier_ = "ethernet-segment-identifier";
    public static final int    _election_wait_time = 135011933;
    public static final String _election_wait_time_ = "election-wait-time";
    public static final int    _bgp_parameters = 1386998958;
    public static final String _bgp_parameters_ = "bgp-parameters";
    public static final int    _vpn_target = 481105398;
    public static final String _vpn_target_ = "vpn-target";
    public static final int    _single_active = 1992672583;
    public static final String _single_active_ = "single-active";
    public static final int    _interface_status = 1493757347;
    public static final String _interface_status_ = "interface-status";
    public static final int    _vlan = 71481437;
    public static final String _vlan_ = "vlan";
    public static final int    _ead_evi_route = 188776668;
    public static final String _ead_evi_route_ = "ead-evi-route";
    public static final int    _df = 524515631;
    public static final String _df_ = "df";
    public static final int    _status = 1950810920;
    public static final String _status_ = "status";
    public static final int    _df_election_method = 1270090193;
    public static final String _df_election_method_ = "df-election-method";
    public static final int    _route_distinguisher = 1746433546;
    public static final String _route_distinguisher_ = "route-distinguisher";
    public static final int    _backbone_src_mac = 81791468;
    public static final String _backbone_src_mac_ = "backbone-src-mac";
    public static final int    _revertive = 1569418781;
    public static final String _revertive_ = "revertive";
    public static final int    _ip_address = 36594129;
    public static final String _ip_address_ = "ip-address";
    public static final int    _all_active = 288111384;
    public static final String _all_active_ = "all-active";
    public static final int    _service_type = 1145594576;
    public static final String _service_type_ = "service-type";
    public static final int    _df_election = 1402038193;
    public static final String _df_election_ = "df-election";
    public static final int    _ac = 1692617166;
    public static final String _ac_ = "ac";
    public static final int    _ac_or_pw = 957137655;
    public static final String _ac_or_pw_ = "ac-or-pw";
    public static final int    _esi_label = 1224322524;
    public static final String _esi_label_ = "esi-label";
    public static final int    _all_active_mode = 932680099;
    public static final String _all_active_mode_ = "all-active-mode";
    public static final int    _rd_rt = 1022311765;
    public static final String _rd_rt_ = "rd-rt";
    public static final int    _service_identifier = 1427442523;
    public static final String _service_identifier_ = "service-identifier";
    public static final int    _ethernet_segments = 455551498;
    public static final String _ethernet_segments_ = "ethernet-segments";
    public static final int    _pbb_parameters = 687406024;
    public static final String _pbb_parameters_ = "pbb-parameters";
    public static final int    _name = 1998270519;
    public static final String _name_ = "name";
    public static final int    _route_target_type = 1412747313;
    public static final String _route_target_type_ = "route-target-type";
    public static final int    _single_active_mode = 352747173;
    public static final String _single_active_mode_ = "single-active-mode";
    public static final int    _common = 12796818;
    public static final String _common_ = "common";
    public static final int    _member = 387693123;
    public static final String _member_ = "member";
    public static final int    _route_target = 472721783;
    public static final String _route_target_ = "route-target";
    public static final int    _preference = 393138131;
    public static final String _preference_ = "preference";
    public static final int    _ethernet_segment = 356593910;
    public static final String _ethernet_segment_ = "ethernet-segment";
    public static final int    _pw = 1136209932;
    public static final String _pw_ = "pw";
    public static final int    _active_mode = 379652077;
    public static final String _active_mode_ = "active-mode";
}
