/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ../load-dir/l3vpn-svc.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.example.nokianspl3vpn.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module l3vpn-svc.yang */
public class l3vpnSvc extends ConfNamespace {
    public static final int hash = 1279167971;
    public int hash() {
        return l3vpnSvc.hash;
    }

    public static final String id = "_nokia-nsp-l3vpn-nc-1.0:nokia-nsp-l3vpn-nc-1.0#http://www.nokia.com/ietf-l3vpn-ntw:l3vpn-ntw/vpn-services";
    public String id() {
        return l3vpnSvc.id;
    }

    public static final String uri = "_nokia-nsp-l3vpn-nc-1.0:nokia-nsp-l3vpn-nc-1.0#http://www.nokia.com/ietf-l3vpn-ntw:l3vpn-ntw/vpn-services";
    public String uri() {
        return l3vpnSvc.uri;
    }

    public String xmlUri() {
        return ConfNamespace.truncateToXMLUri(l3vpnSvc.uri);
    }

    public static final String prefix = "l3vpn-svc";
    public String prefix() {
        return l3vpnSvc.prefix;
    }

    public l3vpnSvc() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

    public static final int    _routing_protocols = 1456255638;
    public static final String _routing_protocols_ = "routing-protocols";
    public static final int    _ipv4 = 268057062;
    public static final String _ipv4_ = "ipv4";
    public static final int    _connection = 1134114300;
    public static final String _connection_ = "connection";
    public static final int    _svc_output_bandwidth = 1065362088;
    public static final String _svc_output_bandwidth_ = "svc-output-bandwidth";
    public static final int    _devices = 270307409;
    public static final String _devices_ = "devices";
    public static final int    _vpn_target = 481105398;
    public static final String _vpn_target_ = "vpn-target";
    public static final int    _peer_status = 2008420880;
    public static final String _peer_status_ = "peer-status";
    public static final int    _vpn_attachment = 363199070;
    public static final String _vpn_attachment_ = "vpn-attachment";
    public static final int    _site_id = 1504125779;
    public static final String _site_id_ = "site-id";
    public static final int    _dot1q_vlan_tagged = 193818157;
    public static final String _dot1q_vlan_tagged_ = "dot1q-vlan-tagged";
    public static final int    _l3vpn_svc = 593629653;
    public static final String _l3vpn_svc_ = "l3vpn-svc";
    public static final int    _location = 1827424758;
    public static final String _location_ = "location";
    public static final int    _vpn_service = 1055968467;
    public static final String _vpn_service_ = "vpn-service";
    public static final int    _address_allocation_type = 1985129786;
    public static final String _address_allocation_type_ = "address-allocation-type";
    public static final int    _site_role = 1195406870;
    public static final String _site_role_ = "site-role";
    public static final int    _sites = 280052322;
    public static final String _sites_ = "sites";
    public static final int    _site_network_access_id = 1100367278;
    public static final String _site_network_access_id_ = "site-network-access-id";
    public static final int    _vpn_policy_id = 182903099;
    public static final String _vpn_policy_id_ = "vpn-policy-id";
    public static final int    _device = 617911018;
    public static final String _device_ = "device";
    public static final int    _vpn_policy = 1025722019;
    public static final String _vpn_policy_ = "vpn-policy";
    public static final int    _site_network_accesses = 1757943133;
    public static final String _site_network_accesses_ = "site-network-accesses";
    public static final int    _addresses = 1825332052;
    public static final String _addresses_ = "addresses";
    public static final int    _status = 1950810920;
    public static final String _status_ = "status";
    public static final int    _site_network_access = 1354428188;
    public static final String _site_network_access_ = "site-network-access";
    public static final int    _vpn_targets = 140988191;
    public static final String _vpn_targets_ = "vpn-targets";
    public static final int    _vpn_services = 420699127;
    public static final String _vpn_services_ = "vpn-services";
    public static final int    _device_id = 669279939;
    public static final String _device_id_ = "device-id";
    public static final int    _locations = 1179950026;
    public static final String _locations_ = "locations";
    public static final int    _tagged_interface = 1105325482;
    public static final String _tagged_interface_ = "tagged-interface";
    public static final int    _address_family = 203507431;
    public static final String _address_family_ = "address-family";
    public static final int    _svc_mtu = 59128295;
    public static final String _svc_mtu_ = "svc-mtu";
    public static final int    _entries = 1782358652;
    public static final String _entries_ = "entries";
    public static final int    _vpn_policies = 2070014031;
    public static final String _vpn_policies_ = "vpn-policies";
    public static final int    _rd = 1976848467;
    public static final String _rd_ = "rd";
    public static final int    _type = 2040883914;
    public static final String _type_ = "type";
    public static final int    _peer_as = 542003455;
    public static final String _peer_as_ = "peer-as";
    public static final int    _vpn_id = 1043646672;
    public static final String _vpn_id_ = "vpn-id";
    public static final int    _port_id = 411479338;
    public static final String _port_id_ = "port-id";
    public static final int    _router_id = 519485925;
    public static final String _router_id_ = "router-id";
    public static final int    _peer_description = 1747769655;
    public static final String _peer_description_ = "peer-description";
    public static final int    _autonomous_system = 299737889;
    public static final String _autonomous_system_ = "autonomous-system";
    public static final int    _management = 1308506682;
    public static final String _management_ = "management";
    public static final int    _svc_input_bandwidth = 1555967831;
    public static final String _svc_input_bandwidth_ = "svc-input-bandwidth";
    public static final int    _admin_enabled = 1699111814;
    public static final String _admin_enabled_ = "admin-enabled";
    public static final int    _ip_connection = 789735093;
    public static final String _ip_connection_ = "ip-connection";
    public static final int    _service = 855380710;
    public static final String _service_ = "service";
    public static final int    _provider_address = 1039400294;
    public static final String _provider_address_ = "provider-address";
    public static final int    _vpn = 1300042178;
    public static final String _vpn_ = "vpn";
    public static final int    _tq_type = 1407941797;
    public static final String _tq_type_ = "tq-type";
    public static final int    _location_id = 517526331;
    public static final String _location_id_ = "location-id";
    public static final int    _site_bearer = 292121906;
    public static final String _site_bearer_ = "site-bearer";
    public static final int    _route_target_type = 1412747313;
    public static final String _route_target_type_ = "route-target-type";
    public static final int    _cvlan_id = 1965303353;
    public static final String _cvlan_id_ = "cvlan-id";
    public static final int    _site = 407467135;
    public static final String _site_ = "site";
    public static final int    _device_reference = 500432060;
    public static final String _device_reference_ = "device-reference";
    public static final int    _encapsulation_type = 671206547;
    public static final String _encapsulation_type_ = "encapsulation-type";
    public static final int    _routing_protocol = 667412728;
    public static final String _routing_protocol_ = "routing-protocol";
    public static final int    _route_target = 472721783;
    public static final String _route_target_ = "route-target";
    public static final int    _id = 1279252765;
    public static final String _id_ = "id";
    public static final int    _peer_address = 2130238605;
    public static final String _peer_address_ = "peer-address";
    public static final int    _bearer = 1710416560;
    public static final String _bearer_ = "bearer";
    public static final int    _prefix_length = 524393771;
    public static final String _prefix_length_ = "prefix-length";
}
