/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ../load-dir/tailf-ned-id-nokia-nsp-l3vpn-nc-1.0.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.example.nokianspl3vpn.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module tailf-ned-id-nokia-nsp-l3vpn-nc-1.0.yang */
public class tailfNedIdNokiaNspL3vpnNc1_0 extends ConfNamespace {
    public static final int hash = 13225761;
    public int hash() {
        return tailfNedIdNokiaNspL3vpnNc1_0.hash;
    }

    public static final String id = "http://tail-f.com/ns/ned-id/nokia-nsp-l3vpn-nc-1.0";
    public String id() {
        return tailfNedIdNokiaNspL3vpnNc1_0.id;
    }

    public static final String uri = "http://tail-f.com/ns/ned-id/nokia-nsp-l3vpn-nc-1.0";
    public String uri() {
        return tailfNedIdNokiaNspL3vpnNc1_0.uri;
    }

    public String xmlUri() {
        return ConfNamespace.truncateToXMLUri(tailfNedIdNokiaNspL3vpnNc1_0.uri);
    }

    public static final String prefix = "nokia-nsp-l3vpn-nc-1.0";
    public String prefix() {
        return tailfNedIdNokiaNspL3vpnNc1_0.prefix;
    }

    public tailfNedIdNokiaNspL3vpnNc1_0() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

    public static final int    _nokia_nsp_l3vpn_nc_10x2e0 = 1075548468;
    public static final String _nokia_nsp_l3vpn_nc_10x2e0_ = "nokia-nsp-l3vpn-nc-1.0";
}
