/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ../load-dir/tailf-ned-id-nokia-nsp-l3vpn-nc.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.example.nokianspl3vpn.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module tailf-ned-id-nokia-nsp-l3vpn-nc.yang */
public class tailfNedIdNokiaNspL3vpnNc extends ConfNamespace {
    public static final int hash = 1695637270;
    public int hash() {
        return tailfNedIdNokiaNspL3vpnNc.hash;
    }

    public static final String id = "http://tail-f.com/ns/ned-id/nokia-nsp-l3vpn-nc";
    public String id() {
        return tailfNedIdNokiaNspL3vpnNc.id;
    }

    public static final String uri = "http://tail-f.com/ns/ned-id/nokia-nsp-l3vpn-nc";
    public String uri() {
        return tailfNedIdNokiaNspL3vpnNc.uri;
    }

    public String xmlUri() {
        return ConfNamespace.truncateToXMLUri(tailfNedIdNokiaNspL3vpnNc.uri);
    }

    public static final String prefix = "nokia-nsp-l3vpn-nc";
    public String prefix() {
        return tailfNedIdNokiaNspL3vpnNc.prefix;
    }

    public tailfNedIdNokiaNspL3vpnNc() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

    public static final int    _nokia_nsp_l3vpn_nc = 419531738;
    public static final String _nokia_nsp_l3vpn_nc_ = "nokia-nsp-l3vpn-nc";
    public static final int    ned_id = 419531738;
    public static final String ned_id_ = "nokia-nsp-l3vpn-nc:nokia-nsp-l3vpn-nc";
}
